json.average_current_maturity submissions_aggregator.current_averages_hash
json.average_target_maturity submissions_aggregator.target_averages_hash
json.current_submissions_array submissions_aggregator.current_averages_array
json.target_submissions_array submissions_aggregator.target_averages_array
